# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rmatsuka < rmatsuka@student.42tokyo.jp>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/04/07 12:59:59 by rmatsuka          #+#    #+#              #
#    Updated: 2021/12/24 15:52:41 by rmatsuka         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	=	libft.a
SRCS	=	ft_strlen.c \
			ft_strcmp.c \
			ft_strncmp.c \
			ft_atoi.c \
			ft_isalpha.c \
			ft_isdigit.c \
			ft_isalnum.c \
			ft_isascii.c \
			ft_isprint.c \
			ft_toupper.c \
			ft_tolower.c \
			ft_memcmp.c \
			ft_strdup.c \
			ft_substr.c \
			ft_strchr.c \
			ft_strrchr.c \
			ft_strnstr.c \
			ft_strjoin.c \
			ft_memset.c \
			ft_memmove.c \
			ft_memcpy.c \
			ft_memccpy.c \
			ft_memchr.c \
			ft_calloc.c \
			ft_bzero.c \
			ft_strlcpy.c \
			ft_strlcat.c \
			ft_strtrim.c \
			ft_split.c \
			ft_itoa.c \
			ft_strmapi.c \
			ft_putchar_fd.c \
			ft_putstr_fd.c \
			ft_putendl_fd.c \
			ft_putnbr_fd.c \
			free_strjoin.c \
			safe_free.c \
			get_next_line.c

OBJS	=	$(SRCS:.c=.o)
RM		=	rm -f
LIBC	=	ar rcs
CC		= 	gcc
CFLAGS	=	-Wall -Wextra -Werror


all:		$(NAME)

$(NAME):	$(OBJS)
			$(LIBC) $(NAME) $(OBJS)

clean:
		$(RM) $(OBJS)

fclean:		clean
			$(RM) $(NAME)

re:			fclean all

.PHONY:		all clean fclean re
